#!/usr/bin/env bash
# Ralph-loop wrapper — drives LOOP_QUEUE.md items autonomously.
# Generated by the ralph-loop skill for the Steinmetz multi-tenancy hardening
# roadmap (HARDENING_ROADMAP.md). Customize variables at the top if needed.
# Pre-iteration: writes LOOP_HANDOFF.md; runs work agent; reads STATUS.
# If done: runs verify agent; rolls back via git reset --hard on failure.
# Per-iteration: standardized tag commit + push (if remote).
set -uo pipefail

# --- Config ------------------------------------------------------------------
QUEUE=LOOP_QUEUE.md
HANDOFF=LOOP_HANDOFF.md
JOURNAL=LOOP_JOURNAL.md
ALERTS=LOOP_ALERTS.md
ATTEMPTS_DIR=.loop-attempts

MODEL="claude-opus-4-7"
WORK_TIMEOUT=30m
VERIFY_TIMEOUT=10m
MAX_ATTEMPTS=5
MAX_TOTAL_ITERS=200
SLEEP_BETWEEN=5
BUDGET_FLAGS=()   # e.g. (--max-budget-usd 3)

# --- Pre-flight --------------------------------------------------------------
[ -f "$QUEUE" ] || { echo "Missing $QUEUE in $(pwd)"; exit 1; }
[ -f HARDENING_ROADMAP.md ] || { echo "Run from a directory containing HARDENING_ROADMAP.md"; exit 1; }
git rev-parse --git-dir >/dev/null 2>&1 \
  || { echo "Not a git repo."; exit 1; }
command -v claude >/dev/null \
  || { echo "'claude' CLI not on PATH."; exit 1; }
command -v timeout >/dev/null \
  || { echo "'timeout' not on PATH (install GNU coreutils)."; exit 1; }

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "ERROR: working tree is dirty. The loop uses 'git reset --hard' for rollback —"
  echo "       any uncommitted changes would be destroyed on a failed verify."
  echo "       Commit or stash first, then re-run."
  exit 1
fi

if git remote get-url origin >/dev/null 2>&1; then
  HAS_REMOTE=1
  echo "Remote 'origin' detected: $(git remote get-url origin) — iterations will be pushed."
else
  HAS_REMOTE=0
  echo "No 'origin' remote — iterations will commit locally only."
fi

mkdir -p "$ATTEMPTS_DIR"
touch "$JOURNAL" "$ALERTS"

# --- Helpers -----------------------------------------------------------------
next_queue_line() { grep -n '^- \[ \]' "$QUEUE" | head -1; }
read_field() {
  grep -i "^$1:" "$HANDOFF" 2>/dev/null | tail -1 | sed "s/^$1://i" | xargs
}
extract_feature_num() {
  # Pulls the leading numeric identifier (e.g. "1.1", "2.3", "3.4") from item_text
  echo "$1" | grep -oE '[0-9]+(\.[0-9]+)*' | head -1
}
truncate_to() {
  local max="$1"; local s="$2"
  if [ "${#s}" -gt "$max" ]; then echo "${s:0:$((max-1))}…"; else echo "$s"; fi
}

push_if_remote() {
  [ "$HAS_REMOTE" = 1 ] || return 0
  local branch; branch=$(git rev-parse --abbrev-ref HEAD)
  git push -u origin "$branch" >/dev/null 2>&1 \
    || echo "[$(date -Iseconds)] WARN: push failed for $branch" >> "$ALERTS"
}

loop_commit() {
  local tag_kind="$1" feature_num="$2" summary="$3" body="$4"
  local short_summary; short_summary=$(truncate_to 120 "$summary")
  local subject="[${tag_kind}: Roadmap feature ${feature_num} - ${short_summary}]"
  git add -A >/dev/null 2>&1
  if git diff --cached --quiet; then
    return 0
  fi
  git commit -m "$subject" -m "$body" >/dev/null 2>&1 \
    || echo "[$(date -Iseconds)] WARN: loop_commit failed for feature $feature_num" >> "$ALERTS"
  push_if_remote
}

# --- Main loop ---------------------------------------------------------------
total=0
while : ; do
  total=$((total + 1))
  if [ "$total" -gt "$MAX_TOTAL_ITERS" ]; then
    echo "Hit MAX_TOTAL_ITERS=$MAX_TOTAL_ITERS. Stopping."
    break
  fi

  line=$(next_queue_line) || true
  if [ -z "$line" ]; then
    echo "No more pending items in $QUEUE. Exiting."
    break
  fi

  line_no=${line%%:*}
  item_text=${line#*:}
  feature_num=$(extract_feature_num "$item_text")
  slug=$(echo "$item_text" | tr -cd '[:alnum:]' | head -c 32)
  attempt_file="$ATTEMPTS_DIR/$slug"
  attempt=$(cat "$attempt_file" 2>/dev/null || echo 0)
  attempt=$((attempt + 1))
  echo "$attempt" > "$attempt_file"

  if [ "$attempt" -gt "$MAX_ATTEMPTS" ]; then
    sed -i "${line_no}s/- \[ \]/- [!]/" "$QUEUE"
    echo "[$(date -Iseconds)] BLOCKED: $item_text (max attempts)" >> "$ALERTS"
    loop_commit "Unsuccessful ship" "$feature_num" \
      "exhausted $MAX_ATTEMPTS attempts" \
      "Auto-blocked by loop after $MAX_ATTEMPTS failed attempts. See $ALERTS for history. Manual review needed before un-marking [!]."
    rm -f "$attempt_file"
    continue
  fi

  cat > "$HANDOFF" <<EOF
## Current item (from $QUEUE line $line_no)
$item_text

## Attempt
$attempt of $MAX_ATTEMPTS

## Context to load before working
- HARDENING_ROADMAP.md   (the infrastructure roadmap this queue is derived from — read the section matching the item's "§N.N" pointer end-to-end before touching code)
- ROADMAP.md             (the product roadmap — context for which features the hardening work has to keep working; don't add product features from here)
- STATE.md               (current build cursor — what's wired today, recent decisions, gotchas)
- AGENTS.md              (project conventions; treat as authoritative)
- CLAUDE.md              (re-exports AGENTS.md — same source of truth)
- supabase/schema.sql    (canonical schema; user has to paste any changes you make into Supabase — call that out in your summary if you change it)
- $QUEUE                 (this queue you're working from)
- recent tail of $JOURNAL

## Protocol
1. Read the context above plus the acceptance criteria nested under the
   current item in $QUEUE, and the matching §N.N section of HARDENING_ROADMAP.md.
2. Implement the item against those acceptance criteria. Run \`npm run build\`
   (and any other checks the criteria name) before concluding.
3. Commit your code changes with a descriptive conventional-commit message.
4. Overwrite $HANDOFF to end with EXACTLY these fields, one per line:
   STATUS: done | partial
   SUMMARY: <1 sentence, will be embedded in the loop's tag commit>
   NEXT_STEPS: <only if partial; concrete handoff for the next agent>
   ACCEPTANCE: <which criteria pass, which don't>
   Do NOT commit $HANDOFF — the loop owns the bookkeeping commit.

## Constraints
- Do NOT modify the opencode fork at /home/agent/opencode. Permission tightening goes in the workspace opencode.jsonc; auth gating goes in front of opencode, not inside it. Keep our fork clean against upstream dev.
- Do NOT modify zap source at /home/agent/zap in end-user mode. Features are user-space Python that imports from zap.
- Do NOT use opencode.ai hosted layers (no Big Pickle, no OpenCode Zen, no OpenCode Go free models). Direct providers only.
- Do NOT introduce containers, orchestrators, or a second VM. Everything in HARDENING_ROADMAP.md runs as Linux users + systemd units on the existing machine. Single-VM is the explicit target end state; if you think an item needs more than that, surface it in NEXT_STEPS — the escalation lives in a separate doc (TIER3_EXPANSION.md) and is out of scope here.
- Do NOT re-architect the MCP-as-tools model. \`may_I_proceed\` (item 2.2) is the only way grid-app gates per-tool execution; do not introduce a parallel "operations are HTTP endpoints" catalog.
- Do NOT add a custom opencode fork divergence. If a hardening item seems to require editing the fork, surface it in NEXT_STEPS and ship the rest.
- Do NOT use emojis in user-facing UI or in code unless the user explicitly asked. This includes commit messages and doc files you add.
- Next.js 16.2.6 breaks: \`cookies()\` / \`headers()\` / \`params\` / \`searchParams\` are async (must \`await\`); \`middleware.ts\` is renamed \`proxy.ts\` with an exported \`proxy()\` function; Turbopack is the default; \`next lint\` is removed. Read node_modules/next/dist/docs/ before writing route-handler / middleware-shaped code.
- Bring-your-own keys: never commit secrets. Supabase service-role key lives in \`.env.local\`. OpenRouter shared key lives in opencode's env. Per-user OpenRouter keys go in \`provider_keys\` (item 1.4) once that ships.
- If you edit \`supabase/schema.sql\`, call it out loudly in SUMMARY — the user has to paste the new SQL into Supabase before the change is live; verify steps that depend on the new table will fail until they do.
- Per-user isolation rule: features/skills/chats are per-user, never committed to zap or opencode git history. Storage is filesystem (\`/home/agent/grid-workspaces/<id>/\`) + Supabase (RLS-gated tables).
- The product roadmap (ROADMAP.md) is out of scope for this queue. Don't pick up feature work even if you notice gaps.
EOF

  echo ">>> [$total] WORK: $item_text (attempt $attempt)"
  pre_sha=$(git rev-parse HEAD)

  timeout "$WORK_TIMEOUT" claude -p \
    --model "$MODEL" \
    --dangerously-skip-permissions \
    "${BUDGET_FLAGS[@]}" \
    "Read $HANDOFF and follow its Protocol exactly." || true

  status=$(read_field STATUS)
  summary=$(read_field SUMMARY)
  next_steps=$(read_field NEXT_STEPS)
  acceptance=$(read_field ACCEPTANCE)
  [ -z "$summary" ] && summary="(no summary written by agent)"

  post_work_sha=$(git rev-parse HEAD)

  if [ "$status" != "done" ]; then
    echo ">>> partial → will retry on next iteration"
    body=$(printf "Status: partial (attempt %s of %s)\n\nSummary: %s\n\nNext steps: %s\n\nAcceptance: %s\n\nUnderlying commits (kept for next attempt):\n%s" \
      "$attempt" "$MAX_ATTEMPTS" "$summary" "${next_steps:-(none recorded)}" "${acceptance:-(none recorded)}" \
      "$(git log --oneline "${pre_sha}..HEAD" 2>/dev/null || echo '(none)')")
    loop_commit "Unsuccessful ship" "$feature_num" "$summary" "$body"
    echo "[$(date -Iseconds)] PARTIAL: $item_text (attempt $attempt)" >> "$ALERTS"
    sleep "$SLEEP_BETWEEN"
    continue
  fi

  if [ "$pre_sha" = "$post_work_sha" ]; then
    echo ">>> STATUS=done but HEAD unchanged — treating as unsuccessful"
    body=$(printf "Status: claimed done but no commit made (attempt %s).\n\nSummary: %s\n\nAcceptance: %s" \
      "$attempt" "$summary" "${acceptance:-(none recorded)}")
    loop_commit "Unsuccessful ship" "$feature_num" "claimed done but no code committed" "$body"
    echo "[$(date -Iseconds)] WARN: $item_text — STATUS=done, HEAD unchanged" >> "$ALERTS"
    sleep "$SLEEP_BETWEEN"
    continue
  fi

  # --- Verify phase ----------------------------------------------------------
  echo ">>> VERIFY: $item_text (commit $post_work_sha)"
  timeout "$VERIFY_TIMEOUT" claude -p \
    --model "$MODEL" \
    --dangerously-skip-permissions \
    "${BUDGET_FLAGS[@]}" \
    "The previous agent claims the current item in $HANDOFF is done at commit $post_work_sha.
Verify by running its acceptance criteria, \`npm run build\`, and any smoke
tests the criteria name. Some items touch the host system (useradd, systemd,
quotaon) — for those, verify the in-repo plumbing exists (schema rows,
template files committed, helper functions wired) rather than executing
host-mutating commands; the handoff should call out anything that must be
applied on the VM manually.
If anything is broken, attempt ONE small fix and re-check.
If still broken, run: git reset --hard ${pre_sha}
Append exactly one line to $HANDOFF: 'VERIFIED: yes' or 'VERIFIED: no' or 'VERIFIED: reverted'.
Do NOT commit $HANDOFF — the loop will." || true

  verified=""
  if [ -f "$HANDOFF" ]; then verified=$(read_field VERIFIED); fi
  post_verify_sha=$(git rev-parse HEAD)

  if [ "$verified" != "yes" ] && [ "$post_verify_sha" = "$post_work_sha" ]; then
    echo ">>> verify did not reset; loop forcing 'git reset --hard $pre_sha'"
    git reset --hard "$pre_sha" >/dev/null 2>&1 || true
    verified="${verified:-reverted}"
  fi

  case "$verified" in
    yes)
      sed -i "${line_no}s/- \[ \]/- [x]/" "$QUEUE"
      if [ "$attempt" = "1" ]; then tag="Successful ship"; else tag="Successful rewrite"; fi
      body=$(printf "Status: shipped on attempt %s of %s.\n\nSummary: %s\n\nAcceptance: %s\n\nUnderlying commits:\n%s" \
        "$attempt" "$MAX_ATTEMPTS" "$summary" "${acceptance:-(none recorded)}" \
        "$(git log --oneline "${pre_sha}..HEAD" 2>/dev/null || echo '(none)')")
      loop_commit "$tag" "$feature_num" "$summary" "$body"
      rm -f "$attempt_file"
      echo "[$(date -Iseconds)] DONE: $item_text" >> "$ALERTS"
      ;;
    reverted)
      body=$(printf "Status: code reverted to %s; agent's claim of done did not survive verify.\n\nSummary: %s\n\nNext steps: %s\n\nAcceptance (last reported): %s" \
        "$pre_sha" "$summary" "${next_steps:-(none recorded)}" "${acceptance:-(none recorded)}")
      loop_commit "Unsuccessful ship" "$feature_num" "verify reverted: $summary" "$body"
      echo "[$(date -Iseconds)] REVERTED: $item_text (attempt $attempt)" >> "$ALERTS"
      ;;
    no|*)
      sed -i "${line_no}s/- \[ \]/- [!]/" "$QUEUE"
      body=$(printf "Status: verify inconclusive ('%s'); code reverted to %s.\n\nSummary: %s\n\nNext steps: %s" \
        "$verified" "$pre_sha" "$summary" "${next_steps:-(needs manual review)}")
      loop_commit "Unsuccessful ship" "$feature_num" "verify broken/inconclusive: $summary" "$body"
      echo "[$(date -Iseconds)] BROKEN: $item_text (verify='$verified')" >> "$ALERTS"
      rm -f "$attempt_file"
      ;;
  esac
  sleep "$SLEEP_BETWEEN"
done
