#!/usr/bin/env bash
# Ralph-loop wrapper — drives LOOP_QUEUE.md items autonomously.
# Generated by the ralph-loop skill. Customize variables at the top if needed.
# Pre-iteration: writes LOOP_HANDOFF.md; runs work agent; reads STATUS.
# If done: runs verify agent; rolls back via git reset --hard on failure.
# Per-iteration: standardized tag commit + push (if remote).
set -uo pipefail

# --- Config ------------------------------------------------------------------
QUEUE=LOOP_QUEUE.md
HANDOFF=LOOP_HANDOFF.md
JOURNAL=LOOP_JOURNAL.md
ALERTS=LOOP_ALERTS.md
ATTEMPTS_DIR=.loop-attempts

MODEL="claude-opus-4-7"
WORK_TIMEOUT=30m
VERIFY_TIMEOUT=10m
MAX_ATTEMPTS=5
MAX_TOTAL_ITERS=200
SLEEP_BETWEEN=5
BUDGET_FLAGS=()   # e.g. (--max-budget-usd 3)

# Throttle / fast-fail guard. `claude -p` can exit in seconds without writing
# STATUS when the Max subscription's 5-hour or weekly rate-limit kicks in (the
# error wording changes; a regex alone is unreliable). The duration heuristic
# (`elapsed < MIN_REAL_RUN_SECS` + no completion field) catches silent hits the
# regex misses. Both produce a sleep-and-retry of the SAME attempt — they do
# NOT count against MAX_ATTEMPTS. Without this, a 3-minute throttle window can
# burn through 5 attempts on 3 items and auto-block them all (see 2026-05-26
# items 4/5/6 in the GPU-parity loop).
RATE_LIMIT_REGEX='rate.?limit|429|too many requests|usage limit|weekly limit|5.hour limit|please (wait|try again)|try again later|quota exceeded|exceeded.*limit|overloaded|service unavailable|503|api error|connection (reset|refused|timed out)'
MIN_REAL_RUN_SECS=60        # treat sub-60s exits with no completion field as suspect
THROTTLE_WAIT_SECS=1800     # sleep 30 min before retrying the same attempt
MAX_THROTTLE_WAITS=24       # 24 × 30m = 12h max throttle wait per attempt
WORK_LOG=/tmp/ralph-loop-work.log
VERIFY_LOG=/tmp/ralph-loop-verify.log

# --- Pre-flight --------------------------------------------------------------
[ -f "$QUEUE" ] || { echo "Missing $QUEUE in $(pwd)"; exit 1; }
git rev-parse --git-dir >/dev/null 2>&1 \
  || { echo "Not a git repo."; exit 1; }
command -v claude >/dev/null \
  || { echo "'claude' CLI not on PATH."; exit 1; }
command -v timeout >/dev/null \
  || { echo "'timeout' not on PATH (install GNU coreutils)."; exit 1; }

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "ERROR: working tree is dirty. The loop uses 'git reset --hard' for rollback —"
  echo "       any uncommitted changes would be destroyed on a failed verify."
  echo "       Commit or stash first, then re-run."
  exit 1
fi

if git remote get-url origin >/dev/null 2>&1; then
  HAS_REMOTE=1
  echo "Remote 'origin' detected: $(git remote get-url origin) — iterations will be pushed."
else
  HAS_REMOTE=0
  echo "No 'origin' remote — iterations will commit locally only."
fi

mkdir -p "$ATTEMPTS_DIR"
touch "$JOURNAL" "$ALERTS"

# --- Helpers -----------------------------------------------------------------
next_queue_line() { grep -n '^- \[ \]' "$QUEUE" | head -1; }
read_field() {
  grep -i "^$1:" "$HANDOFF" 2>/dev/null | tail -1 | sed "s/^$1://i" | xargs
}
extract_feature_num() {
  # Pulls the leading numeric identifier (e.g. "1", "1.2", "11.8") from item_text
  echo "$1" | grep -oE '[0-9]+(\.[0-9]+)*' | head -1
}
truncate_to() {
  local max="$1"; local s="$2"
  if [ "${#s}" -gt "$max" ]; then echo "${s:0:$((max-1))}…"; else echo "$s"; fi
}

push_if_remote() {
  [ "$HAS_REMOTE" = 1 ] || return 0
  local branch; branch=$(git rev-parse --abbrev-ref HEAD)
  git push -u origin "$branch" >/dev/null 2>&1 \
    || echo "[$(date -Iseconds)] WARN: push failed for $branch" >> "$ALERTS"
}

run_claude_attempt() {
  # Args: <timeout_spec> <log_file> <prompt> [completion_field]
  # Wraps `claude -p` with throttle / fast-fail retry. Re-issues the SAME
  # invocation (does not consume an attempt) when:
  #   - the log matches RATE_LIMIT_REGEX, OR
  #   - the call returned in less than MIN_REAL_RUN_SECS and the agent did
  #     not write the expected completion field (STATUS for work, VERIFIED
  #     for verify).
  # Sleeps THROTTLE_WAIT_SECS between retries, gives up after
  # MAX_THROTTLE_WAITS and lets the caller treat it as a real failed attempt.
  local tmo="$1" log="$2" prompt="$3" completion_field="${4:-STATUS}"
  local waits=0
  while : ; do
    : > "$log"
    local t0; t0=$(date +%s)
    timeout "$tmo" claude -p \
      --model "$MODEL" \
      --dangerously-skip-permissions \
      "${BUDGET_FLAGS[@]}" \
      "$prompt" >>"$log" 2>&1 || true
    local elapsed=$(( $(date +%s) - t0 ))

    local saw_completion; saw_completion=$(read_field "$completion_field")
    local saw_rl=0
    if grep -qiE "$RATE_LIMIT_REGEX" "$log" 2>/dev/null; then saw_rl=1; fi
    local fast_blank=0
    if [ -z "$saw_completion" ] && [ "$elapsed" -lt "$MIN_REAL_RUN_SECS" ]; then
      fast_blank=1
    fi

    if [ -z "$saw_completion" ] && { [ "$saw_rl" = 1 ] || [ "$fast_blank" = 1 ]; }; then
      waits=$((waits + 1))
      if [ "$waits" -gt "$MAX_THROTTLE_WAITS" ]; then
        echo "[$(date -Iseconds)] THROTTLE GIVE-UP: $waits sleeps × ${THROTTLE_WAIT_SECS}s — letting caller count this as a real failed attempt." >> "$ALERTS"
        echo ">>> Throttle retry budget exhausted; proceeding as a counted attempt."
        return 0
      fi
      local why=""
      [ "$saw_rl" = 1 ]    && why="${why}rate-limit-regex "
      [ "$fast_blank" = 1 ] && why="${why}fast-blank(${elapsed}s)"
      echo ">>> THROTTLED ($waits/$MAX_THROTTLE_WAITS) [$why]; sleeping ${THROTTLE_WAIT_SECS}s then retrying the SAME attempt..."
      echo "[$(date -Iseconds)] THROTTLE: sleep ${THROTTLE_WAIT_SECS}s ($waits/$MAX_THROTTLE_WAITS) [$why]" >> "$ALERTS"
      sleep "$THROTTLE_WAIT_SECS"
      continue
    fi
    return 0
  done
}

loop_commit() {
  local tag_kind="$1" feature_num="$2" summary="$3" body="$4"
  local short_summary; short_summary=$(truncate_to 120 "$summary")
  local subject="[${tag_kind}: Roadmap feature ${feature_num} - ${short_summary}]"
  git add -A >/dev/null 2>&1
  if git diff --cached --quiet; then
    return 0
  fi
  git commit -m "$subject" -m "$body" >/dev/null 2>&1 \
    || echo "[$(date -Iseconds)] WARN: loop_commit failed for feature $feature_num" >> "$ALERTS"
  push_if_remote
}

# --- Main loop ---------------------------------------------------------------
total=0
while : ; do
  total=$((total + 1))
  if [ "$total" -gt "$MAX_TOTAL_ITERS" ]; then
    echo "Hit MAX_TOTAL_ITERS=$MAX_TOTAL_ITERS. Stopping."
    break
  fi

  line=$(next_queue_line) || true
  if [ -z "$line" ]; then
    echo "No more pending items in $QUEUE. Exiting."
    break
  fi

  line_no=${line%%:*}
  item_text=${line#*:}
  feature_num=$(extract_feature_num "$item_text")
  slug=$(echo "$item_text" | tr -cd '[:alnum:]' | head -c 32)
  attempt_file="$ATTEMPTS_DIR/$slug"
  attempt=$(cat "$attempt_file" 2>/dev/null || echo 0)
  attempt=$((attempt + 1))
  echo "$attempt" > "$attempt_file"

  if [ "$attempt" -gt "$MAX_ATTEMPTS" ]; then
    sed -i "${line_no}s/- \[ \]/- [!]/" "$QUEUE"
    echo "[$(date -Iseconds)] BLOCKED: $item_text (max attempts)" >> "$ALERTS"
    loop_commit "Unsuccessful ship" "$feature_num" \
      "exhausted $MAX_ATTEMPTS attempts" \
      "Auto-blocked by loop after $MAX_ATTEMPTS failed attempts. See $ALERTS for history. Manual review needed before un-marking [!]."
    rm -f "$attempt_file"
    continue
  fi

  cat > "$HANDOFF" <<EOF
## Current item (from $QUEUE line $line_no)
$item_text

## Attempt
$attempt of $MAX_ATTEMPTS

## Context to load before working
- GPU_UNBLOCK_ROADMAP.md          (full roadmap for this loop; the queue item points to a §section here)
- GPU_PARITY_ROADMAP.md           (precedent roadmap; §Phase B.4 / §Phase C.5 / §Phase C.6 are the original specs for items 1-3)
- AGENTS.md                       (project rules: harness-first principle, no-zap-edits in end-user mode, no-emoji, no-deps, conventional commits)
- CLAUDE.md                       (one-line include of AGENTS.md)
- STATE.md                        (current build cursor — what's freshly shipped, what's wired)
- infra/modal/solver_app.py       (deployed Modal app; \`_run_solve\` returns the payload items 1-2 must adapt)
- infra/modal/PARITY_REPORT.md    (item 9's parity numbers — historical 4.22% LMP diff on ieee-30 is the baseline for items 2 and 4)
- lib/modal-solver.ts             (TS client; \`SolveResult\` interface mirrors the payload shape on the frontend)
- scripts/smoke_dispatch.py       (CPU baseline \`run_dispatch\` returns \`(outcome, pnet, snapshots, used_solver, elapsed)\` — item 2 extends this; item 3 callers depend on it)
- scripts/run_artifact.py         (\`build_run_view_spec\` is the downstream consumer; item 1's adapter output must satisfy this contract)
- scripts/_gpu_parity_report.py   (item 9; \`gpu_solve()\` is the reference HTTP-call code for item 2)
- scripts/user-mcp-server.py      (item 7; \`_solve_via_modal()\` is the agent-path GPU caller — item 4 smokes it, item 5 cross-checks it against \`--gpu\` CLI)
- scripts/seed_networks.py        (item 3 target — adds \`--gpu\` flag, forwards through run_dispatch)
- scripts/ingest_pypsa_folder.py  (item 3 target — same pattern)
- data/networks/ieee-30/          (the canonical test network referenced by every acceptance bullet)
- $QUEUE            (the queue you're working from)
- recent tail of $JOURNAL

## Protocol
1. Read the context above plus any acceptance criteria nested under the
   current item in $QUEUE.
2. Implement the item against those acceptance criteria. Run \`python scripts/smoke_dispatch.py data/networks/ieee-30 --hours 1 && npm run build\`
   (and any other checks the criteria name) before concluding.
3. Commit your code changes with a descriptive conventional-commit message.
4. Overwrite $HANDOFF to end with EXACTLY these fields, one per line:
   STATUS: done | partial
   SUMMARY: <1 sentence, will be embedded in the loop's tag commit>
   NEXT_STEPS: <only if partial; concrete handoff for the next agent>
   ACCEPTANCE: <which criteria pass, which don't>
   Do NOT commit $HANDOFF — the loop owns the bookkeeping commit.

## Constraints
- Do NOT modify /home/agent/zap source. In end-user mode the agent is forbidden from editing zap (AGENTS.md). All work in this loop is in /home/agent/grid-app/scripts/ — zap is consumed as a library.
- Do NOT delete or alter the CPU path's return shape. \`run_dispatch\` must still return \`(outcome, pnet, snapshots, used_solver, elapsed)\` for CPU callers. GPU adapts to CPU, never the other way around (GPU_PARITY_ROADMAP.md §Design).
- Do NOT introduce a CPU-vs-GPU auto-tiering heuristic. \`--gpu\` is a manual choice everywhere. Auto-routing is explicitly out of scope (see GPU_PARITY_ROADMAP §Design).
- Do NOT use opencode.ai hosted services (Big Pickle, OpenCode Zen, OpenCode Go free models). Direct providers only.
- Do NOT commit secrets. \`.env.local\` holds ZAP_SOLVER_API_KEY, Supabase service-role keys, and OpenRouter keys — never stage them.
- Do NOT add npm or pip dependencies a few lines of code could replace.
- No emojis in code or user-facing strings.
- Modal redeploys take 3-5 min after image changes — none of items 1-5 should need a redeploy (Modal endpoint is unchanged from item 3 of the prior loop). If you find yourself running \`modal deploy\`, stop and re-read the acceptance criteria.
- The previous loop archived its state under \`.loop-archive/gpu-parity-2026-05/\`. Read it if you need history on items 4-6's earlier failed attempts (the original §Phase B.4 / C.5 / C.6 — now renumbered 1-3 in this loop). Do not modify .loop-archive.
- If \`ZAP_SOLVER_MODAL_URL\` or \`ZAP_SOLVER_API_KEY\` is missing from \`.env.local\`, items 2, 4, and 5 cannot complete. Report this as the genuine blocker rather than rubber-stamping ACCEPTANCE.
EOF

  echo ">>> [$total] WORK: $item_text (attempt $attempt)"
  pre_sha=$(git rev-parse HEAD)

  run_claude_attempt "$WORK_TIMEOUT" "$WORK_LOG" \
    "Read $HANDOFF and follow its Protocol exactly." \
    STATUS

  status=$(read_field STATUS)
  summary=$(read_field SUMMARY)
  next_steps=$(read_field NEXT_STEPS)
  acceptance=$(read_field ACCEPTANCE)
  [ -z "$summary" ] && summary="(no summary written by agent)"

  post_work_sha=$(git rev-parse HEAD)

  if [ "$status" != "done" ]; then
    echo ">>> partial → will retry on next iteration"
    body=$(printf "Status: partial (attempt %s of %s)\n\nSummary: %s\n\nNext steps: %s\n\nAcceptance: %s\n\nUnderlying commits (kept for next attempt):\n%s" \
      "$attempt" "$MAX_ATTEMPTS" "$summary" "${next_steps:-(none recorded)}" "${acceptance:-(none recorded)}" \
      "$(git log --oneline "${pre_sha}..HEAD" 2>/dev/null || echo '(none)')")
    loop_commit "Unsuccessful ship" "$feature_num" "$summary" "$body"
    echo "[$(date -Iseconds)] PARTIAL: $item_text (attempt $attempt)" >> "$ALERTS"
    sleep "$SLEEP_BETWEEN"
    continue
  fi

  if [ "$pre_sha" = "$post_work_sha" ]; then
    echo ">>> STATUS=done but HEAD unchanged — treating as unsuccessful"
    body=$(printf "Status: claimed done but no commit made (attempt %s).\n\nSummary: %s\n\nAcceptance: %s" \
      "$attempt" "$summary" "${acceptance:-(none recorded)}")
    loop_commit "Unsuccessful ship" "$feature_num" "claimed done but no code committed" "$body"
    echo "[$(date -Iseconds)] WARN: $item_text — STATUS=done, HEAD unchanged" >> "$ALERTS"
    sleep "$SLEEP_BETWEEN"
    continue
  fi

  # --- Verify phase ----------------------------------------------------------
  echo ">>> VERIFY: $item_text (commit $post_work_sha)"
  run_claude_attempt "$VERIFY_TIMEOUT" "$VERIFY_LOG" \
    "The previous agent claims the current item in $HANDOFF is done at commit $post_work_sha.
Verify by running its acceptance criteria, \`python scripts/smoke_dispatch.py data/networks/ieee-30 --hours 1 && npm run build\`, and any smoke
tests the criteria name. If anything is broken, attempt ONE small fix and re-check.
If still broken, run: git reset --hard ${pre_sha}
Append exactly one line to $HANDOFF: 'VERIFIED: yes' or 'VERIFIED: no' or 'VERIFIED: reverted'.
Do NOT commit $HANDOFF — the loop will." \
    VERIFIED

  verified=""
  if [ -f "$HANDOFF" ]; then verified=$(read_field VERIFIED); fi
  post_verify_sha=$(git rev-parse HEAD)

  if [ "$verified" != "yes" ] && [ "$post_verify_sha" = "$post_work_sha" ]; then
    echo ">>> verify did not reset; loop forcing 'git reset --hard $pre_sha'"
    git reset --hard "$pre_sha" >/dev/null 2>&1 || true
    verified="${verified:-reverted}"
  fi

  case "$verified" in
    yes)
      sed -i "${line_no}s/- \[ \]/- [x]/" "$QUEUE"
      if [ "$attempt" = "1" ]; then tag="Successful ship"; else tag="Successful rewrite"; fi
      body=$(printf "Status: shipped on attempt %s of %s.\n\nSummary: %s\n\nAcceptance: %s\n\nUnderlying commits:\n%s" \
        "$attempt" "$MAX_ATTEMPTS" "$summary" "${acceptance:-(none recorded)}" \
        "$(git log --oneline "${pre_sha}..HEAD" 2>/dev/null || echo '(none)')")
      loop_commit "$tag" "$feature_num" "$summary" "$body"
      rm -f "$attempt_file"
      echo "[$(date -Iseconds)] DONE: $item_text" >> "$ALERTS"
      ;;
    reverted)
      body=$(printf "Status: code reverted to %s; agent's claim of done did not survive verify.\n\nSummary: %s\n\nNext steps: %s\n\nAcceptance (last reported): %s" \
        "$pre_sha" "$summary" "${next_steps:-(none recorded)}" "${acceptance:-(none recorded)}")
      loop_commit "Unsuccessful ship" "$feature_num" "verify reverted: $summary" "$body"
      echo "[$(date -Iseconds)] REVERTED: $item_text (attempt $attempt)" >> "$ALERTS"
      ;;
    no|*)
      sed -i "${line_no}s/- \[ \]/- [!]/" "$QUEUE"
      body=$(printf "Status: verify inconclusive ('%s'); code reverted to %s.\n\nSummary: %s\n\nNext steps: %s" \
        "$verified" "$pre_sha" "$summary" "${next_steps:-(needs manual review)}")
      loop_commit "Unsuccessful ship" "$feature_num" "verify broken/inconclusive: $summary" "$body"
      echo "[$(date -Iseconds)] BROKEN: $item_text (verify='$verified')" >> "$ALERTS"
      rm -f "$attempt_file"
      ;;
  esac
  sleep "$SLEEP_BETWEEN"
done
