#!/usr/bin/env bash
# Ralph-loop wrapper — drives LOOP_QUEUE.md items autonomously.
# Generated by the ralph-loop skill. Customize variables at the top if needed.
# Pre-iteration: writes LOOP_HANDOFF.md; runs work agent; reads STATUS.
# If done: runs verify agent; rolls back via git reset --hard on failure.
# Per-iteration: standardized tag commit + push (if remote).
set -uo pipefail

# --- Config ------------------------------------------------------------------
QUEUE=LOOP_QUEUE.md
HANDOFF=LOOP_HANDOFF.md
JOURNAL=LOOP_JOURNAL.md
ALERTS=LOOP_ALERTS.md
ATTEMPTS_DIR=.loop-attempts

MODEL="claude-opus-4-7"
WORK_TIMEOUT=30m
VERIFY_TIMEOUT=10m
MAX_ATTEMPTS=5
MAX_TOTAL_ITERS=200
SLEEP_BETWEEN=5
BUDGET_FLAGS=()   # e.g. (--max-budget-usd 3)

# Rate-limit handling. When the underlying `claude -p` invocation hits a
# 5-hour or weekly Max-subscription limit, it fails fast with an error
# the loop would otherwise swallow as an "Unsuccessful ship". Instead,
# detect the rate-limit error and SLEEP, retrying within the same
# attempt (so it doesn't consume one of MAX_ATTEMPTS). The loop keeps
# waiting in 30-minute pulses until either the limit clears or the
# total waits exceed MAX_RATE_LIMIT_WAITS (default: 24 × 30m = 12h).
RATE_LIMIT_WAIT_SECS=1800
MAX_RATE_LIMIT_WAITS=24

# --- Pre-flight --------------------------------------------------------------
[ -f "$QUEUE" ] || { echo "Missing $QUEUE in $(pwd)"; exit 1; }
git rev-parse --git-dir >/dev/null 2>&1 \
  || { echo "Not a git repo."; exit 1; }
command -v claude >/dev/null \
  || { echo "'claude' CLI not on PATH."; exit 1; }
command -v timeout >/dev/null \
  || { echo "'timeout' not on PATH (install GNU coreutils)."; exit 1; }

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "ERROR: working tree is dirty. The loop uses 'git reset --hard' for rollback —"
  echo "       any uncommitted changes would be destroyed on a failed verify."
  echo "       Commit or stash first, then re-run."
  exit 1
fi

if git remote get-url origin >/dev/null 2>&1; then
  HAS_REMOTE=1
  echo "Remote 'origin' detected: $(git remote get-url origin) — iterations will be pushed."
else
  HAS_REMOTE=0
  echo "No 'origin' remote — iterations will commit locally only."
fi

mkdir -p "$ATTEMPTS_DIR"
touch "$JOURNAL" "$ALERTS"

# --- Helpers -----------------------------------------------------------------
next_queue_line() { grep -n '^- \[ \]' "$QUEUE" | head -1; }
read_field() {
  grep -i "^$1:" "$HANDOFF" 2>/dev/null | tail -1 | sed "s/^$1://i" | xargs
}
extract_feature_num() {
  # Pulls the leading numeric identifier (e.g. "1", "1.2", "11.8") from item_text
  echo "$1" | grep -oE '[0-9]+(\.[0-9]+)*' | head -1
}
truncate_to() {
  local max="$1"; local s="$2"
  if [ "${#s}" -gt "$max" ]; then echo "${s:0:$((max-1))}…"; else echo "$s"; fi
}

is_rate_limited() {
  local log_file="$1"
  [ -f "$log_file" ] || return 1
  # Patterns the Claude CLI / API surface for 5-hour, weekly, and
  # generic 429s. Case-insensitive; tolerates the various wordings
  # we've observed in Max-subscription rate-limit errors.
  grep -qiE 'rate.?limit|429|too many requests|usage limit|weekly limit|5-hour limit|please (wait|try again)|try again later|quota exceeded|exceeded.*limit' "$log_file"
}

run_claude_with_rate_limit_retry() {
  # Args: <timeout_spec> <log_file> <prompt> [completion_field]
  # Re-invokes `claude -p` after sleeping when a rate-limit error is
  # detected. Returns once a non-rate-limited result is produced (or
  # we hit MAX_RATE_LIMIT_WAITS).
  #
  # Rate-limit detection: combines a regex match on the log AND the
  # absence of the completion field (default STATUS for work phase,
  # VERIFIED for verify phase). The completion-field guard prevents
  # false positives when the agent's own legitimate output mentions
  # phrases like "rate limit" or "429" (item 10's bug-hunt probes
  # exactly these UI states). Real rate-limit failures never reach the
  # protocol step that writes the completion field.
  local tmo="$1" log="$2" prompt="$3" completion_field="${4:-STATUS}"
  local rl_waits=0
  while : ; do
    : > "$log"
    timeout "$tmo" claude -p \
      --model "$MODEL" \
      --dangerously-skip-permissions \
      "${BUDGET_FLAGS[@]}" \
      "$prompt" >>"$log" 2>&1 || true

    if is_rate_limited "$log" && [ -z "$(read_field "$completion_field")" ]; then
      rl_waits=$((rl_waits + 1))
      if [ "$rl_waits" -gt "$MAX_RATE_LIMIT_WAITS" ]; then
        echo "[$(date -Iseconds)] RATE-LIMIT GIVE-UP: $rl_waits × ${RATE_LIMIT_WAIT_SECS}s and still rate-limited — exiting loop. Resume by relaunching ./loop.sh once limits reset." >> "$ALERTS"
        echo ">>> Hit MAX_RATE_LIMIT_WAITS=$MAX_RATE_LIMIT_WAITS. Exiting cleanly so you can resume later."
        exit 0
      fi
      echo ">>> RATE-LIMITED ($rl_waits/$MAX_RATE_LIMIT_WAITS); sleeping ${RATE_LIMIT_WAIT_SECS}s, will retry the SAME attempt..."
      echo "[$(date -Iseconds)] RATE-LIMITED: sleep ${RATE_LIMIT_WAIT_SECS}s ($rl_waits/$MAX_RATE_LIMIT_WAITS) — same attempt will retry" >> "$ALERTS"
      sleep "$RATE_LIMIT_WAIT_SECS"
      continue
    fi
    break
  done
}

per_item_work_timeout() {
  # 1.5× default work budget for item 10 and its 10.x children
  # (frontend validation / bug-hunting). Everything else uses default.
  case "$1" in
    10|10.*) echo "45m" ;;
    *)       echo "$WORK_TIMEOUT" ;;
  esac
}

per_item_verify_timeout() {
  case "$1" in
    10|10.*) echo "15m" ;;
    *)       echo "$VERIFY_TIMEOUT" ;;
  esac
}

push_if_remote() {
  [ "$HAS_REMOTE" = 1 ] || return 0
  local branch; branch=$(git rev-parse --abbrev-ref HEAD)
  git push -u origin "$branch" >/dev/null 2>&1 \
    || echo "[$(date -Iseconds)] WARN: push failed for $branch" >> "$ALERTS"
}

loop_commit() {
  local tag_kind="$1" feature_num="$2" summary="$3" body="$4"
  local short_summary; short_summary=$(truncate_to 120 "$summary")
  local subject="[${tag_kind}: Roadmap feature ${feature_num} - ${short_summary}]"
  git add -A >/dev/null 2>&1
  if git diff --cached --quiet; then
    return 0
  fi
  git commit -m "$subject" -m "$body" >/dev/null 2>&1 \
    || echo "[$(date -Iseconds)] WARN: loop_commit failed for feature $feature_num" >> "$ALERTS"
  push_if_remote
}

# --- Main loop ---------------------------------------------------------------
total=0
while : ; do
  total=$((total + 1))
  if [ "$total" -gt "$MAX_TOTAL_ITERS" ]; then
    echo "Hit MAX_TOTAL_ITERS=$MAX_TOTAL_ITERS. Stopping."
    break
  fi

  line=$(next_queue_line) || true
  if [ -z "$line" ]; then
    echo "No more pending items in $QUEUE. Exiting."
    break
  fi

  line_no=${line%%:*}
  item_text=${line#*:}
  feature_num=$(extract_feature_num "$item_text")
  slug=$(echo "$item_text" | tr -cd '[:alnum:]' | head -c 32)
  attempt_file="$ATTEMPTS_DIR/$slug"
  attempt=$(cat "$attempt_file" 2>/dev/null || echo 0)
  attempt=$((attempt + 1))
  echo "$attempt" > "$attempt_file"

  if [ "$attempt" -gt "$MAX_ATTEMPTS" ]; then
    sed -i "${line_no}s/- \[ \]/- [!]/" "$QUEUE"
    echo "[$(date -Iseconds)] BLOCKED: $item_text (max attempts)" >> "$ALERTS"
    loop_commit "Unsuccessful ship" "$feature_num" \
      "exhausted $MAX_ATTEMPTS attempts" \
      "Auto-blocked by loop after $MAX_ATTEMPTS failed attempts. See $ALERTS for history. Manual review needed before un-marking [!]."
    rm -f "$attempt_file"
    continue
  fi

  cat > "$HANDOFF" <<EOF
## Current item (from $QUEUE line $line_no)
$item_text

## Attempt
$attempt of $MAX_ATTEMPTS

## Context to load before working
- GPU_PARITY_ROADMAP.md           (full roadmap; the item in $QUEUE points to a §section here)
- AGENTS.md                       (project rules, layered architecture, harness-first principle)
- CLAUDE.md                       (one-line include of AGENTS.md)
- STATE.md                        (current build cursor — read tail for what's freshly shipped)
- infra/modal/README.md           (existing Modal deploy + wire-up notes)
- infra/modal/solver_app.py       (deployed Modal app; the body of \`_run_solve\` is the GPU call site)
- lib/modal-solver.ts             (TS client; \`SolveResult\` interface lives here)
- scripts/smoke_dispatch.py       (CPU baseline: \`run_dispatch\` returns \`(outcome, pnet, snapshots, used_solver, elapsed)\`)
- scripts/run_artifact.py         (\`build_run_row\` / \`build_run_view_spec\` — downstream consumer of any solve outcome)
- scripts/user-mcp-server.py      (per-user MCP server — where new agent-callable tools register)
- components/runs/RunView.tsx     (renders run artifacts; provenance fields surface here)
- /home/agent/zap/zap/admm/       (ADMMSolver / ADMMLayer source — Phase A.1)
- /home/agent/zap/zap/importers/pypsa.py  (\`load_pypsa_network\`, \`parse_generators\` — Phase A.2)
- /home/agent/zap/zap/tests/      (existing zap test layout — pattern for the new regression tests)
- $QUEUE                          (the queue you're working from)
- recent tail of $JOURNAL

## Protocol
1. Read the context above plus any acceptance criteria nested under the
   current item in $QUEUE.
2. Implement the item against those acceptance criteria. Run the relevant
   smoke for the item (e.g. \`python scripts/smoke_dispatch.py data/networks/ieee-30\`
   for Phase C items, \`npm run build\` for TS/renderer items in Phase B/D,
   \`pytest /home/agent/zap/zap/tests/\` for Phase A items, \`modal deploy
   infra/modal/solver_app.py\` after touching the Modal app) before concluding.
3. Commit your code changes with a descriptive conventional-commit message.
4. Overwrite $HANDOFF to end with EXACTLY these fields, one per line:
   STATUS: done | partial
   SUMMARY: <1 sentence, will be embedded in the loop's tag commit>
   NEXT_STEPS: <only if partial; concrete handoff for the next agent>
   ACCEPTANCE: <which criteria pass, which don't>
   BLOCKED: yes  ← ONLY include this line if the item is genuinely
                   blocked by an environmental constraint (not "this is
                   hard" or "I'm not sure"). When BLOCKED: yes is set,
                   the loop marks the item [!] immediately and stops
                   retrying — no more attempts. Use NEXT_STEPS to
                   describe what you tried and what blocked you.
                   Be skeptical of your own "impossible" claim:
                   enumerate concrete approaches and try the most
                   promising before declaring BLOCKED.
   Do NOT commit $HANDOFF — the loop owns the bookkeeping commit.

## Constraints
- Cross-repo items (1, 2) edit /home/agent/zap. Commit zap changes INSIDE
  /home/agent/zap with a conventional-commit subject and push to origin if
  configured, BEFORE returning STATUS: done. The grid-app loop's tag commit
  only captures grid-app changes. Do not stage zap files into grid-app.
- Otherwise honour AGENTS.md: "in end-user mode the agent must not modify
  zap source." Items 1-2 are the explicit maintainer-mode exceptions for
  this loop; everything else stays out of /home/agent/zap.
- Do not commit secrets. .env.local holds ZAP_SOLVER_API_KEY — never stage
  it. Same for OpenRouter / Supabase service-role keys.
- Don't bypass \`may_I_proceed\` / \`release\` in user-mcp-server.py for the
  new \`solve_opf\` tool — match the existing admission pattern.
- No emojis in code or user-facing strings.
- Don't add npm dependencies a few lines of code could replace.
- For new Next.js routes / server code, remember this is Next 16
  (\`cookies()/headers()/params/searchParams\` are async; \`proxy.ts\` not
  \`middleware.ts\`; Turbopack is default).
- Modal deploys take 3-5 minutes on first call after image changes; budget
  for it but do not skip the deploy when an item's acceptance demands a
  fresh endpoint.
- Do NOT introduce a CPU-vs-GPU auto-tiering heuristic. The roadmap is
  explicit: \`--gpu\` is a manual choice everywhere. (Phase E item 9
  produces the parity data needed to inform a future heuristic; that
  heuristic is out of scope for this loop.)
- Do NOT delete the CPU path or alter its return shape. GPU adapts to
  match CPU, not the other way around.
- If an acceptance criterion can't be verified scriptably in this
  environment (e.g. the Modal endpoint is down), say so explicitly in
  ACCEPTANCE: rather than rubber-stamping.
- Phase F mechanic: \`LOOP_QUEUE.md\` contains a sentinel line
  \`<==NEXT-LINE-IS-TERMINAL==>\` immediately above item 99 (the demos
  page). Item 99 is the **fixed terminus** and must remain the last
  \`- [ ]\` line in the queue at all times. Item 10 (and only item 10)
  is authorised to insert new \`- [ ]\` queue items — they go
  IMMEDIATELY ABOVE the sentinel line, never below it. Number them
  \`10.x\` (e.g. \`- [ ] 10.1 Fix overflow on artifact list\`) so their
  provenance is unambiguous. Edits to LOOP_QUEUE.md from item 10 are
  staged + committed by the work agent as part of that iteration's
  commit (the loop's bookkeeping commit will pick them up).
- For Phase F items, the test account credentials
  (\`STEINMETZ_TEST_ACCOUNT_EMAIL\` / \`STEINMETZ_TEST_ACCOUNT_PASSWORD\`)
  live in \`.env.local\` only and must never be staged. Verify
  \`.env.local\` is in \`.gitignore\` before writing them.
EOF

  echo ">>> [$total] WORK: $item_text (attempt $attempt)"
  pre_sha=$(git rev-parse HEAD)

  item_work_timeout=$(per_item_work_timeout "$feature_num")
  item_verify_timeout=$(per_item_verify_timeout "$feature_num")
  work_log=$(mktemp)
  run_claude_with_rate_limit_retry \
    "$item_work_timeout" "$work_log" \
    "Read $HANDOFF and follow its Protocol exactly." \
    STATUS
  rm -f "$work_log"

  status=$(read_field STATUS)
  blocked=$(read_field BLOCKED)
  summary=$(read_field SUMMARY)
  next_steps=$(read_field NEXT_STEPS)
  acceptance=$(read_field ACCEPTANCE)
  [ -z "$summary" ] && summary="(no summary written by agent)"

  post_work_sha=$(git rev-parse HEAD)

  # Agent-declared environmental block. Skip retries; mark [!] immediately.
  if [ "$blocked" = "yes" ]; then
    sed -i "${line_no}s/- \[ \]/- [!]/" "$QUEUE"
    body=$(printf "Status: agent declared BLOCKED — environmental block, not retried.\n\nSummary: %s\n\nDetails / what was tried: %s\n\nAcceptance: %s\n\nUnderlying commits (if any):\n%s" \
      "$summary" "${next_steps:-(none recorded)}" "${acceptance:-(none recorded)}" \
      "$(git log --oneline "${pre_sha}..HEAD" 2>/dev/null || echo '(none)')")
    loop_commit "Unsuccessful ship" "$feature_num" "agent declared blocked: $summary" "$body"
    echo "[$(date -Iseconds)] AGENT_BLOCKED: $item_text — agent wrote BLOCKED: yes" >> "$ALERTS"
    rm -f "$attempt_file"
    sleep "$SLEEP_BETWEEN"
    continue
  fi

  if [ "$status" != "done" ]; then
    echo ">>> partial → will retry on next iteration"
    body=$(printf "Status: partial (attempt %s of %s)\n\nSummary: %s\n\nNext steps: %s\n\nAcceptance: %s\n\nUnderlying commits (kept for next attempt):\n%s" \
      "$attempt" "$MAX_ATTEMPTS" "$summary" "${next_steps:-(none recorded)}" "${acceptance:-(none recorded)}" \
      "$(git log --oneline "${pre_sha}..HEAD" 2>/dev/null || echo '(none)')")
    loop_commit "Unsuccessful ship" "$feature_num" "$summary" "$body"
    echo "[$(date -Iseconds)] PARTIAL: $item_text (attempt $attempt)" >> "$ALERTS"
    sleep "$SLEEP_BETWEEN"
    continue
  fi

  if [ "$pre_sha" = "$post_work_sha" ]; then
    echo ">>> STATUS=done but HEAD unchanged — treating as unsuccessful"
    body=$(printf "Status: claimed done but no commit made (attempt %s).\n\nSummary: %s\n\nAcceptance: %s" \
      "$attempt" "$summary" "${acceptance:-(none recorded)}")
    loop_commit "Unsuccessful ship" "$feature_num" "claimed done but no code committed" "$body"
    echo "[$(date -Iseconds)] WARN: $item_text — STATUS=done, HEAD unchanged" >> "$ALERTS"
    sleep "$SLEEP_BETWEEN"
    continue
  fi

  # --- Verify phase ----------------------------------------------------------
  echo ">>> VERIFY: $item_text (commit $post_work_sha)"
  verify_log=$(mktemp)
  run_claude_with_rate_limit_retry \
    "$item_verify_timeout" "$verify_log" \
    "The previous agent claims the current item in $HANDOFF is done at commit $post_work_sha.
Verify by running its acceptance criteria. Choose the right smoke for the
item: \`npm run build\` for TS / renderer changes, \`python scripts/smoke_dispatch.py
data/networks/ieee-30 --hours 4\` (with or without --gpu, as the item demands)
for solve-path changes, \`pytest /home/agent/zap/zap/tests/\` for Phase A zap fixes,
and \`modal run infra/modal/solver_app.py::smoke\` for Modal handler changes.
For Phase A items, also verify the zap commit landed inside /home/agent/zap.
If anything is broken, attempt ONE small fix and re-check.
If still broken, run: git reset --hard ${pre_sha}
Append exactly one line to $HANDOFF: 'VERIFIED: yes' or 'VERIFIED: no' or 'VERIFIED: reverted'.
Do NOT commit $HANDOFF — the loop will." \
    VERIFIED
  rm -f "$verify_log"

  verified=""
  if [ -f "$HANDOFF" ]; then verified=$(read_field VERIFIED); fi
  post_verify_sha=$(git rev-parse HEAD)

  if [ "$verified" != "yes" ] && [ "$post_verify_sha" = "$post_work_sha" ]; then
    echo ">>> verify did not reset; loop forcing 'git reset --hard $pre_sha'"
    git reset --hard "$pre_sha" >/dev/null 2>&1 || true
    verified="${verified:-reverted}"
  fi

  case "$verified" in
    yes)
      sed -i "${line_no}s/- \[ \]/- [x]/" "$QUEUE"
      if [ "$attempt" = "1" ]; then tag="Successful ship"; else tag="Successful rewrite"; fi
      body=$(printf "Status: shipped on attempt %s of %s.\n\nSummary: %s\n\nAcceptance: %s\n\nUnderlying commits:\n%s" \
        "$attempt" "$MAX_ATTEMPTS" "$summary" "${acceptance:-(none recorded)}" \
        "$(git log --oneline "${pre_sha}..HEAD" 2>/dev/null || echo '(none)')")
      loop_commit "$tag" "$feature_num" "$summary" "$body"
      rm -f "$attempt_file"
      echo "[$(date -Iseconds)] DONE: $item_text" >> "$ALERTS"
      ;;
    reverted)
      body=$(printf "Status: code reverted to %s; agent's claim of done did not survive verify.\n\nSummary: %s\n\nNext steps: %s\n\nAcceptance (last reported): %s" \
        "$pre_sha" "$summary" "${next_steps:-(none recorded)}" "${acceptance:-(none recorded)}")
      loop_commit "Unsuccessful ship" "$feature_num" "verify reverted: $summary" "$body"
      echo "[$(date -Iseconds)] REVERTED: $item_text (attempt $attempt)" >> "$ALERTS"
      ;;
    no|*)
      sed -i "${line_no}s/- \[ \]/- [!]/" "$QUEUE"
      body=$(printf "Status: verify inconclusive ('%s'); code reverted to %s.\n\nSummary: %s\n\nNext steps: %s" \
        "$verified" "$pre_sha" "$summary" "${next_steps:-(needs manual review)}")
      loop_commit "Unsuccessful ship" "$feature_num" "verify broken/inconclusive: $summary" "$body"
      echo "[$(date -Iseconds)] BROKEN: $item_text (verify='$verified')" >> "$ALERTS"
      rm -f "$attempt_file"
      ;;
  esac
  sleep "$SLEEP_BETWEEN"
done
