import { promises as fs } from "fs"
import path from "path"

// Gated whitepaper route. Inherits the auth gate from `app/app/*` via proxy.ts.
// The markdown is rendered as soft-typeset preformatted text — readable without
// pulling in a markdown-rendering dep. The body is generated by the Steinmetz
// benchmark loop (`reports/build_whitepaper.py` in the zap repo) so this page
// only ever displays auto-derived numbers.
export default async function SteinmetzWhitepaperPage() {
  const file = path.join(
    process.cwd(),
    "app",
    "app",
    "whitepaper",
    "STEINMETZ_WHITEPAPER.md",
  )
  let markdown: string
  try {
    markdown = await fs.readFile(file, "utf8")
  } catch {
    return (
      <div className="h-full overflow-y-auto">
        <div className="max-w-3xl mx-auto w-full px-6 py-12 font-soft text-black/60">
          Whitepaper not staged. Drop{" "}
          <code className="font-mono">STEINMETZ_WHITEPAPER.md</code> into{" "}
          <code className="font-mono">app/app/whitepaper/</code>.
        </div>
      </div>
    )
  }

  return (
    <div className="h-full overflow-y-auto bg-white">
      <article className="max-w-3xl mx-auto w-full px-6 py-10">
        <header className="mb-8 pb-4 border-b border-black/10">
          <p className="font-mark text-xs tracking-wide text-black/40 uppercase">
            Steinmetz · auto-generated
          </p>
          <p className="font-soft text-xs text-black/50 mt-1">
            Every benchmark headline below is rendered from the
            <code className="font-mono mx-1">BenchResult</code>
            JSON sidecar; no number on this page is hand-written.
          </p>
        </header>
        <div className="font-soft text-[15px] leading-relaxed text-black whitespace-pre-wrap">
          {markdown}
        </div>
      </article>
    </div>
  )
}
